jobs: 
  deploy: 
    name: deploy to ec2
    runs-on: ubuntu-latest

    steps: 
      - name: checkout the file
        uses: actions/checkout@v2

      - name: Deploy to server 1
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${ {secrets.PHPKeyPair}}
          REMOTE_HOST: ${ {secrets.ec2-54-90-73-225.compute-1.amazonaws.com}}
          REMOTE_USER: ${ {secrets.ec2-user}}
          TARGET: ${ {secrets./var/www/html}}
